import "./globals.css";
import { useEffect } from "react";
import Cookies from "js-cookie";
import { redirect } from "next/navigation";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const token = Cookies.get("token");
  // console.log(token);
  // if (!token) {
  //   redirect("/login");
  // }

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
