import "./globals.css";
import { redirect } from "next/navigation";
import Link from "next/link";
import Navbar from "@/components/Navbar";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
